services:
  portfolio:
    image: dbouraoui/portfolio:latest
    networks:
      - traefik_webgateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`cool.signacore.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3001" # <- correspond au port exposé par "serve"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

networks:
  traefik_webgateway:
    external: true
